<?php

namespace Woopple\Components\Widgets;

class Navbar extends Widget
{
    // todo: Сделать лучше, чем сейчас.
    public bool $notifications = false;
    public bool $messages = false;
    public bool $fullscreen = false;
    public string $assetDir;

    public array $items = [];
    protected array $leftNavbarItems = [];
    protected array $rightNavbarItems = [];

    const ALIGN_PARAM = 'align';
    const ALIGN_RIGHT = 'right';
    const ALIGN_LEFT = 'left';

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }

    public function init(): void
    {
        array_map(function (array $item) {
            if ($item[self::ALIGN_PARAM] === self::ALIGN_LEFT)
                $this->leftNavbarItems[] = $item;
            else
                $this->rightNavbarItems[] = $item;
        }, $this->items);
    }
}